<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserQuestions', 'doctrine');

/**
 * BaseUserQuestions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $question_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Questions $Questions
 * @property Users $Users
 * 
 * @method integer       getId()          Returns the current record's "id" value
 * @method integer       getUserId()      Returns the current record's "user_id" value
 * @method integer       getQuestionId()  Returns the current record's "question_id" value
 * @method timestamp     getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp     getUpdatedAt()   Returns the current record's "updated_at" value
 * @method Questions     getQuestions()   Returns the current record's "Questions" value
 * @method Users         getUsers()       Returns the current record's "Users" value
 * @method UserQuestions setId()          Sets the current record's "id" value
 * @method UserQuestions setUserId()      Sets the current record's "user_id" value
 * @method UserQuestions setQuestionId()  Sets the current record's "question_id" value
 * @method UserQuestions setCreatedAt()   Sets the current record's "created_at" value
 * @method UserQuestions setUpdatedAt()   Sets the current record's "updated_at" value
 * @method UserQuestions setQuestions()   Sets the current record's "Questions" value
 * @method UserQuestions setUsers()       Sets the current record's "Users" value
 * 
 * @package    damsharas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserQuestions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_questions');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('question_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Questions', array(
             'local' => 'question_id',
             'foreign' => 'id'));

        $this->hasOne('Users', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}