<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Questions', 'doctrine');

/**
 * BaseQuestions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $question
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $Answers
 * @property Doctrine_Collection $Tips
 * @property Doctrine_Collection $UserQuestions
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getQuestion()      Returns the current record's "question" value
 * @method timestamp           getCreatedAt()     Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()     Returns the current record's "updated_at" value
 * @method Doctrine_Collection getAnswers()       Returns the current record's "Answers" collection
 * @method Doctrine_Collection getTips()          Returns the current record's "Tips" collection
 * @method Doctrine_Collection getUserQuestions() Returns the current record's "UserQuestions" collection
 * @method Questions           setId()            Sets the current record's "id" value
 * @method Questions           setQuestion()      Sets the current record's "question" value
 * @method Questions           setCreatedAt()     Sets the current record's "created_at" value
 * @method Questions           setUpdatedAt()     Sets the current record's "updated_at" value
 * @method Questions           setAnswers()       Sets the current record's "Answers" collection
 * @method Questions           setTips()          Sets the current record's "Tips" collection
 * @method Questions           setUserQuestions() Sets the current record's "UserQuestions" collection
 * 
 * @package    damsharas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuestions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('questions');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('question', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Answers', array(
             'local' => 'id',
             'foreign' => 'question_id'));

        $this->hasMany('Tips', array(
             'local' => 'id',
             'foreign' => 'question_id'));

        $this->hasMany('UserQuestions', array(
             'local' => 'id',
             'foreign' => 'question_id'));
    }
}