<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Quesions', 'doctrine');

/**
 * BaseQuesions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $quesion
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $Answers
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getQuesion()    Returns the current record's "quesion" value
 * @method timestamp           getCreatedAt()  Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()  Returns the current record's "updated_at" value
 * @method Doctrine_Collection getAnswers()    Returns the current record's "Answers" collection
 * @method Quesions            setId()         Sets the current record's "id" value
 * @method Quesions            setQuesion()    Sets the current record's "quesion" value
 * @method Quesions            setCreatedAt()  Sets the current record's "created_at" value
 * @method Quesions            setUpdatedAt()  Sets the current record's "updated_at" value
 * @method Quesions            setAnswers()    Sets the current record's "Answers" collection
 * 
 * @package    damsharas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuesions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quesions');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('quesion', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Answers', array(
             'local' => 'id',
             'foreign' => 'quesion_id'));
    }
}