<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tips', 'doctrine');

/**
 * BaseTips
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $question_id
 * @property string $image
 * @property string $tip
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Questions $Questions
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method integer   getQuestionId()  Returns the current record's "question_id" value
 * @method string    getImage()       Returns the current record's "image" value
 * @method string    getTip()         Returns the current record's "tip" value
 * @method timestamp getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp getUpdatedAt()   Returns the current record's "updated_at" value
 * @method Questions getQuestions()   Returns the current record's "Questions" value
 * @method Tips      setId()          Sets the current record's "id" value
 * @method Tips      setQuestionId()  Sets the current record's "question_id" value
 * @method Tips      setImage()       Sets the current record's "image" value
 * @method Tips      setTip()         Sets the current record's "tip" value
 * @method Tips      setCreatedAt()   Sets the current record's "created_at" value
 * @method Tips      setUpdatedAt()   Sets the current record's "updated_at" value
 * @method Tips      setQuestions()   Sets the current record's "Questions" value
 * 
 * @package    damsharas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTips extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tips');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('question_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('tip', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Questions', array(
             'local' => 'question_id',
             'foreign' => 'id'));
    }
}