<?php

/**
 * QuesionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuesionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuesionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Quesions');
    }
}