<?php

/**
 * TipsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipsTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object TipsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Tips');
    }

    public function str_before($subject, $needle) {
        $p = strpos($subject, $needle);
        return substr($subject, 0, $p);
    }

}