<?php

/**
 * UserQuestionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserQuestionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserQuestionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserQuestions');
    }
}