<?php

/**
 * UsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsersTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object UsersTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Users');
    }

    public function func_isEmailExist($email_address) {
        $q = $this->createQuery('u')
                ->where('u.email = ?', $email_address);
        return $q->fetchArray();
    }
    
        public function func_getUserQuestions($email_address) {
        $q = $this->createQuery('u')
                ->innerJoin('u.UserQuestions uq')
                ->andWhere('u.email = ?', $email_address);
        return $q->fetchArray();
    }

}